version: '3'

services:
  example-registry:
    image: registry:2
    ports:
    - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - /home/cmnatic/examples/registry/data:/data
    restart: unless-stopped